server:
  port: 8080

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://ep-aged-feather-ai16v5l7.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: npg_bkpxLu0wPtH9

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:your-email@gmail.com}
    password: ${GMAIL_APP_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: ${JWT_SECRET:8f3e2a91c7d4b6f0e2a8c5d9b1f4e7a3c6d8b2f5e9a1c4d7b0f3e6a9c2d5b8f1e4a7c0d3b6f9e2a5c8d1b4f7}

restaurant-service:
  base-url: ${RESTAURANT_SERVICE_URL:http://localhost:8080}

gateway:
  api-key: ${GATEWAY_API_KEY:6Ob_XlkyOKT0YRTJO8L6uXtFOyeC1Y0YtMRfVFNjgtc}

notification:
  from-email: ${GMAIL_USERNAME:your-email@gmail.com}
  enabled: ${NOTIFICATION_EMAIL_ENABLED:true}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    com.foodexpress.order: DEBUG
    org.springframework.amqp: INFO
